export ES_EMBEDDING_MODEL_ID="<Elasticsearch Embedding Model"
export ES_CLOUD_ID="<Elastic Cloud Id>"
export ES_INDEX="<Elastic Index Name>"
export ES_USERNAME="<Elastic User Name>"
export ES_PASSWORD="<Elastic Password>"
export COHERE_LIGHT_ENDPOINT="<LLM Endpoint Name>"
export AWS_REGION="us-east-1"
