export ES_CLOUD_ID="<Elastic Cloud Id>"
export ES_INDEX="<Elastic Index Name>"
export ES_USERNAME="<Elastic User Name>"
export ES_PASSWORD="<Elastic Password>"
export FLAN_T5_ENDPOINT="<Flan T5 Endpoint Name>"
export FALCON_40B_ENDPOINT="<Falcon 40B Endpoint Name>"
export AWS_REGION="<AWS Region>"
